version: '3.4'

services:
  data:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  interactions:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development