name: Build Docker Image

on:
  workflow_call:
    inputs:
      DOMAIN:
        required: true
        type: string

env:
  registryName: srphmusceacr

jobs:
  build:
    runs-on: ubuntu-latest
    ENVIRONMENT: dev
    steps:
      - name: Checkout Repositorya
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registryName }}.azurecr.io
          username: ${{ env.registryName }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./src
          file: ./src/Seraphim.{{ inputs.DOMAIN }}/Dockerfile
          push: true
          tags: ${{ env.registryName }}.azurecr.io/Seraphim.{{ inputs.DOMAIN }}:${{ github.sha }}