name: Build Deploy and Configure App Service

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '6'

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      webAppName:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: dev
    secrets:
      appSettings:
        required: true
      azureCreds:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Dotnet Build
        run: dotnet build --configuration Release

      - name: Dotnet Publish
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package/Seraphim.${{ inputs.domain }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: seraphim.${{ inputs.domain }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package/src/Seraphim.${{ inputs.domain }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: seraphim.${{ inputs.domain }}

      - name: Authenticate with Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.azureCreds }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.webAppName }}
          package: .

  configure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: deploy
    steps:
      - name: Authenticate with Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.azureCreds }}

      - name: Set Configuration Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ inputs.webAppName }}
          app-settings-json: ${{ secrets.appSettings }}
