name: Configure Web App

on:
  workflow_call:
    inputs:
      webappName:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      appSettings:
        required: true

env:
  registryName: srphmusceacr

jobs:
  configure:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Authenticate with Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Configuration Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ inputs.webappName }}
          app-settings-json: ${{ secrets.appSettings }}