name: Deploy Docker Based Web App

on:
  workflow_call:
    inputs:
      webappName:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  registryName: srphmusceacr

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - name: Authenticate with Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ inputs.webappName }}
      #     images: ${{ env.registryName }}.azurecr.io/seraphim:${{ github.sha }}