name: Deploy Seraphim.Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  builddeployconfigure:
    uses: SeraphGuild/Seraphim/.github/workflows/builddeployconfigure.yaml@main
    with:
      domain: Repository
      webAppName: srphm-repo-usce-as-dev
    secrets:
      appSettings: ${{ secrets.DATA_APP_SETTINGS }}
      azureCreds: ${{ secrets.AZURE_CREDENTIALS }}