name: Deploy Seraphim.Interactions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  builddeployconfigure:
    uses: SeraphGuild/Seraphim/.github/workflows/builddeployconfigure.yaml@main
    with:
      domain: Interactions
      webAppName: srphm-ack-usce-func-dev
    secrets:
      appSettings: ${{ secrets.ACK_APP_SETTINGS }}
      containerRegistryPassword: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      azureCreds: ${{ secrets.AZURE_CREDENTIALS }}
