name: Deploy Seraphim.Interactions

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  builddeployconfigure:
    uses: SeraphGuild/Seraphim/.github/workflows/builddeployconfigure.yaml@main
    with:
      domain: Interactions
      webAppName: srphm-interact-usce-func-dev
    secrets:
      appSettings: ${{ secrets.INTERACTIONS_APP_SETTINGS }}
      azureCreds: ${{ secrets.AZURE_CREDENTIALS }}
