name: Deploy Seraphim.Data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  builddeployconfigure:
    uses: SeraphGuild/Seraphim/.github/workflows/builddeployconfigure.yaml@main
    with:
      domain: Data
      webAppName: srphm-data-usce-as-dev
    secrets:
      appSettings: ${{ secrets.DATA_APP_SETTINGS }}