name: Deploy Seraphim.InteractionAcknowledgement

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  environment: dev
  webAppName: srphm-ack-usce-as-dev
  domain: InteractionAcknowledgement

jobs:
  build:
    uses: SeraphGuild/Seraphim/.github/workflows/buildimage.yaml@main
    with:
      domain: ${{ env.domain }}
      webAppName: ${{ env.webAppName }}
  deploy:
    uses: SeraphGuild/Seraphim/.github/workflows/deployimage.yaml@main
    with:
      webAppName: ${{ env.webAppName }}
      environment: ${{ inputs.environment }}
  configure:
    uses: SeraphGuild/Seraphim/.github/workflows/configurewebapp.yaml@main
    with:
      webAppName: ${{ env.webAppName }}
      environment: ${{ env.environment }}
      appSettings: ${{ secrets.ACK_APP_SETTINGS }}
