name: Deploy Seraphim.InteractionAcknowledgement

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  builddeployconfigure:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: SeraphGuild/Seraphim/.github/workflows/builddeployconfigure.yaml@main
        with:
          domain: InteractionAcknowledgement
          webAppName: srphm-ack-usce-as-dev
          appSettings: ${{ secrets.ACK_APP_SETTINGS }}
